In [1]:
# Working with Python Modules

In [ ]:
!python3 -m pip install numpy
!pip install numpy

In [2]:
import numpy

In [3]:
# from, import, as

In [5]:
import keyword

In [7]:
keyword.kwlist

True

In [8]:
import keyword as kw
kw.kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [12]:
from keyword import kwlist, iskeyword as isk
kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [13]:
isk('if')

True

In [14]:
import numpy as np

In [15]:
a = np.array([])
a

array([], dtype=float64)

In [16]:
b = np.array([3,4,5,6,7])
b

array([3, 4, 5, 6, 7])

In [20]:
len(a), len(b)

(0, 5)

In [21]:
a.dtype

dtype('float64')

In [22]:
b.dtype

dtype('int64')

In [23]:
b.shape

(5,)

In [24]:
b.size

5

In [25]:
a.shape

(0,)

In [26]:
a.ndim

1

In [27]:
b.ndim

1

In [28]:
c = np.array([[2,3,4], [4,5,6], [7,8,9], [10,11,9]])
c

array([[ 2,  3,  4],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11,  9]])

In [29]:
c.shape

(4, 3)

In [32]:
d = np.array([[[2,20],[3,30],[4,40]], 
                [[4,40],[5,50],[6,60]],
                [[7,70],[8,80],[9,90]], 
                [[10,100],[11,110],[9,90]]])
d

array([[[  2,  20],
        [  3,  30],
        [  4,  40]],

       [[  4,  40],
        [  5,  50],
        [  6,  60]],

       [[  7,  70],
        [  8,  80],
        [  9,  90]],

       [[ 10, 100],
        [ 11, 110],
        [  9,  90]]])

In [33]:
d.shape

(4, 3, 2)

In [36]:
c.sum(axis=1)

array([ 9, 15, 24, 30])

In [37]:
c.mean(axis=1)

array([ 3.,  5.,  8., 10.])

In [38]:
c

array([[ 2,  3,  4],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11,  9]])

In [40]:
c[0][1]

3

In [41]:
c[0:2, -1]

array([4, 6])

In [43]:
c[0:2, -1:]

array([[4],
       [6]])