In [3]:
# !python -m pip install numpy

In [2]:
import numpy as np

In [4]:
a = np.array([8,6,5])
a

array([8, 6, 5])

In [5]:
b = np.array([[6,7,8],[2,3,4]])
b

array([[6, 7, 8],
       [2, 3, 4]])

In [6]:
b.shape

(2, 3)

In [7]:
b+5

array([[11, 12, 13],
       [ 7,  8,  9]])

In [8]:
a * 3

array([24, 18, 15])

In [9]:
a.dtype

dtype('int64')

In [11]:
a[0] = 13
a

array([13,  6,  5])

In [12]:
del a[0]

ValueError: cannot delete array elements

In [13]:
k= np.array([[3,8,4],[9,3,5],[11,15,17],[19,31,8]])
k

array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [15]:
k[0,:] = [30,40,50]

In [16]:
k

array([[30, 40, 50],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [18]:
k[:,1] = [401,301,151,311]

In [19]:
k

array([[ 30, 401,  50],
       [  9, 301,   5],
       [ 11, 151,  17],
       [ 19, 311,   8]])

In [21]:
k[:2,1:] = [[202,303],[404,505]]
k

array([[ 22, 202, 303],
       [ 44, 404, 505],
       [ 11, 151,  17],
       [ 19, 311,   8]])

In [25]:
k[4,:] = [[1,1,1]]
k

IndexError: index 4 is out of bounds for axis 0 with size 4

In [24]:
np.append(k,[[1,1,1]], axis = 0) # zero to add row-wise

array([[ 22, 202, 303],
       [ 44, 404, 505],
       [ 11, 151,  17],
       [ 19, 311,   8],
       [  1,   1,   1]])

In [26]:
np.append(k,[[1],[1],[1],[1]], axis = 1)

array([[ 22, 202, 303,   1],
       [ 44, 404, 505,   1],
       [ 11, 151,  17,   1],
       [ 19, 311,   8,   1]])

In [31]:
k

array([[ 22, 202, 303],
       [ 44, 404, 505],
       [ 11, 151,  17],
       [ 19, 311,   8]])

In [34]:
np.delete(k,3,axis=0)

array([[ 22, 202, 303],
       [ 44, 404, 505],
       [ 11, 151,  17]])

In [37]:
k.reshape(6,2)

array([[ 22, 202],
       [303,  44],
       [404, 505],
       [ 11, 151],
       [ 17,  19],
       [311,   8]])

In [38]:
a.dtype

dtype('int64')

In [39]:
a1 = np.array([3.5,3,7])
a1

array([3.5, 3. , 7. ])

In [40]:
a1.dtype

dtype('float64')

In [41]:
a1.astype('uint16')

array([3, 3, 7], dtype=uint16)

In [43]:
k.mean(axis=1)

array([175.66666667, 317.66666667,  59.66666667, 112.66666667])

In [44]:
k.std(axis=1)

array([116.21914166, 197.85572746,  64.62885492, 140.31472561])

In [45]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
np.linspace(1,10,6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [48]:
np.random.randint(1,15,[3,4])

array([[ 8,  7, 12,  4],
       [ 7,  6, 14, 12],
       [ 5,  2,  5,  3]])

In [ ]:
# Nutshell
## We create arrays
# 1. np.array()
# 2. np.ones()
# 3. np.zeros()
# 4. np.arange()
# 5. np.linspace()
# 6. np.random.randint()
## Arrays have some attributes and functions


In [2]:
import numpy as np

In [4]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.zeros((2,3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0]])

In [7]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.linspace(1,10,10, dtype=int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
list(range(1,11,1))

TypeError: 'float' object cannot be interpreted as an integer

In [16]:
np.random.randint(1,6,1)

array([2])

In [20]:
np.random.randint(31,6000,[4,3])

array([[5463, 5399, 3798],
       [4634, 4075,  630],
       [4828, 1339, 2509],
       [ 648, 4777, 2977]])

In [27]:
np.random.seed(54)
np.random.randint(31,6000,[4,3],)

array([[ 929, 3886, 5174],
       [3840, 3423, 2096],
       [5160, 5669, 4744],
       [3350, 4835, 3347]])

In [28]:
np.random.rand(3,4)

array([[0.6714843 , 0.02965701, 0.39156203, 0.40479404],
       [0.18963101, 0.76710564, 0.61672315, 0.92627396],
       [0.32512403, 0.25315435, 0.72021792, 0.99695746]])

In [30]:
r = np.loadtxt('somedata.txt',dtype = str)
r

array(['hi', 'this', 'is', 'a', 'file', 'outside', 'python.'], dtype='<U7')

In [31]:
r = np.loadtxt('moredata.txt')
r

array([[ 45.,  34.,  56.,  78.],
       [ 79.,  80., 104.,  33.]])

In [32]:
p = np.random.rand(3,4)
p

array([[0.30787317, 0.17198668, 0.17538453, 0.16382659],
       [0.58501438, 0.47353556, 0.46075695, 0.23515401],
       [0.85621717, 0.47089378, 0.05458343, 0.99325708]])

In [34]:
np.savetxt('new.txt',p, delimiter=',')