In [1]:
4+5

9

In [ ]:
!python -m pip install numpy

In [2]:
import numpy as np

In [3]:
a = np.array([5,7,8])
a

array([5, 7, 8])

In [4]:
a.shape

(3,)

In [6]:
b = np.array([[5,7,8], [7,3,4]])
b

array([[5, 7, 8],
       [7, 3, 4]])

In [11]:
m = np.array([
        [[4,41],[8,81],[7,71]],
        [[3,31],[1,11],[5,51]],
        [[6,61],[9,91],[13,131]]
    ])

In [13]:
m.shape

(3, 3, 2)

In [8]:
m.shape

(3, 3, 2)

In [9]:
m[:2,-2:,:1]

array([[[8],
        [7]],

       [[1],
        [5]]])

In [10]:
m[-1:,-2:,:]

array([[[  9,  91],
        [ 13, 131]]])

In [18]:
b[0,0]=505
b

array([[505,  55,  55],
       [  7,   3,   4]])

In [22]:
b[:,1] = [45,46]
b

array([[505,  45,  55],
       [  7,  46,   4]])

In [23]:
b + 3

array([[508,  48,  58],
       [ 10,  49,   7]])

In [24]:
b

array([[505,  45,  55],
       [  7,  46,   4]])

In [26]:
b[2:,:] = [1,1,1]

In [27]:
b

array([[505,  45,  55],
       [  7,  46,   4]])

In [28]:
np.append(b, [[1,1,1]], axis = 0) # row

array([[505,  45,  55],
       [  7,  46,   4],
       [  1,   1,   1]])

In [30]:
np.append(b, [[1],[1]], axis = 1) # columns

array([[505,  45,  55,   1],
       [  7,  46,   4,   1]])

In [34]:
np.delete(b, (1,2), axis = 1) # columns

array([[505],
       [  7]])

In [ ]:
# Array Creation Functions
np.array()
np.arange()
np.linspace()
np.ones()
np.zeros()
np.eye()
np.random.randint()