In [1]:
import numpy as np

In [2]:
np.array([4,45,5,6])

array([ 4, 45,  5,  6])

In [3]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(1,11,1.5)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [8]:
list(range(1,11,1.5))

TypeError: 'float' object cannot be interpreted as an integer

In [11]:
print(np.ones((4,5)))
print(np.zeros((4,5)))
print(np.eye(4))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
np.ones((4,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
p = np.ones((3,4))
p

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
p.dtype

dtype('float64')

In [16]:
p.astype(int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [17]:
p

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
# 'uint8', 'uint16','uint32',     'uint64'
# 'int8',  'int16', 'int32',      'int64'
# 'float8', 'float16','float32',  'float64'

In [18]:
p8 = p.astype('uint8')
p8

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=uint8)

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.random.randint(1,100, 5)

array([27, 39, 88, 85, 58])

In [25]:
np.random.randint(1,100, [3,5])

array([[31, 61, 90, 54, 55],
       [21, 66,  4, 55, 48],
       [37, 97, 68, 91, 39]])

In [26]:
np.random.randint(1,100, [3,5])

array([[13, 92, 36, 33, 94],
       [31, 66, 48, 31, 76],
       [55, 73, 70, 96, 60]])

In [30]:
np.random.seed(198)
np.random.randint(1,100, [3,5])

array([[72, 75, 90, 83, 45],
       [ 7, 94, 57, 59, 75],
       [56, 51,  7, 50, 34]])

In [35]:
r = np.random.rand(3,4) * 100
r

array([[23.8911989 , 11.88919938, 93.65814966, 30.59444031],
       [34.89521078, 25.57526662, 96.82146961, 27.51650971],
       [14.19242444, 64.62262996, 56.63287816, 69.74005869]])

In [37]:
np.random.randn(3,4)

array([[ 0.24613809,  1.04756837, -0.39604441, -0.3806349 ],
       [-0.16718159, -0.91624143, -0.14971785,  0.43794515],
       [ 0.29802995,  1.31287226, -2.26125208,  1.61196477]])

In [38]:
import random

In [39]:
random.choice(r)

array([34.89521078, 25.57526662, 96.82146961, 27.51650971])

In [41]:
np.loadtxt('data.txt', dtype='str')

array([['this', 'is', 'a', 'new', 'file'],
       ['here', 'we', 'get', 'some', 'data']], dtype='<U4')

In [43]:
np.loadtxt('data1.txt',delimiter=',')

array([[45., 65., 78., 98.],
       [23., 19.,  3., 88.],
       [ 1.,  4.,  5.,  6.]])

In [45]:
a = np.random.randint(10,1000, [3,6])
a

array([[921, 675, 945, 974, 165, 360],
       [792, 431,  63, 278, 329, 946],
       [ 89,  83, 214,  30, 683, 607]])

In [47]:
np.savetxt('data3.txt', a, delimiter='|', fmt='%d')

In [48]:
a

array([[921, 675, 945, 974, 165, 360],
       [792, 431,  63, 278, 329, 946],
       [ 89,  83, 214,  30, 683, 607]])

In [50]:
sum(sum(a))

8585

In [51]:
a.sum()

8585

In [52]:
a.sum(axis=1)

array([4040, 2839, 1706])

In [53]:
a.sum(axis=0)

array([1802, 1189, 1222, 1282, 1177, 1913])

In [54]:
a.mean(axis=1)

array([673.33333333, 473.16666667, 284.33333333])

In [55]:
a.max(axis=1)

array([974, 946, 683])

In [56]:
a.argmax(axis=1)

array([3, 5, 4])

In [57]:
a

array([[921, 675, 945, 974, 165, 360],
       [792, 431,  63, 278, 329, 946],
       [ 89,  83, 214,  30, 683, 607]])

In [59]:
a.flatten()

array([921, 675, 945, 974, 165, 360, 792, 431,  63, 278, 329, 946,  89,
        83, 214,  30, 683, 607])

In [58]:
a.argmax()

3

In [62]:
a

array([[921, 675, 945, 974, 165, 360],
       [792, 431,  63, 278, 329, 946],
       [ 89,  83, 214,  30, 683, 607]])

In [61]:
np.where(a>3)

(array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]),
 array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]))